### ISSUE TITLE
Show a friendly error message if a profile already exists for the selected date

### ISSUE THREAD

**Issue by gabebw** [gabebw/croniker#53]
This is what happens now:

```
SqlError {sqlState = "23505", sqlExecStatus = FatalError, sqlErrorMsg = "duplicate key value violates unique constraint \"unique_user_date\"", sqlErrorDetail = "Key (user_id, date)=(4, 2016-05-31) already exists.", sqlErrorHint = ""}
```

**Comment by adarsh** [comment]
As a user, I usually just submit a bunch into the queue and want them changed daily. Maybe auto increment the date to next-available? Or handle the error as "hey that date was invalid so we set the next possible one"?

In short, I feel default behavior (for me) would be "line these up to change daily."

**Comment by gabebw** [comment]
Fixed and deployed to production.
