### ISSUE TITLE
Don't let people pick a taken date at all 

### ISSUE THREAD

**Issue by gabebw** [gabebw/croniker#55]
> I _think_ I'd do something with `selectField` and `optionsPairs` as detailed in [the yesod-form docs](https://s3.amazonaws.com/haddock.stackage.org/lts-6.1/yesod-form-1.4.7.1/Yesod-Form-Fields.html#g:4).

Some more discussion in #54.

**Comment by gabebw** [comment]
Using a `<select>` instead of `<input type="date">` does mean that people couldn't select a username too far in advance (since, unlike a date field, there'd have to be hundreds of options in the HTML), but that's probably not a problem. People usually select usernames maybe a month in advance at the most (i.e. 30 options, not hundreds).

I could also use something like [Select2](https://select2.github.io/) to make a 300-item select box nice and pretty.

**Comment by tonyd256** [comment]
How about some sort of custom calendar control that has those dates blacked out? I know that sounds like a lot of work but maybe there is something easy to use out there.

**Comment by gabebw** [comment]
This could be helpful: http://felicegattuso.com/projects/datedropper/

**Comment by gabebw** [comment]
I think the easiest way is to set the default value of the `<input type="date">` to the next available date for that user. That way people can submit the form and never change the date, plus I don't need to add any JS.

**Comment by gabebw** [comment]
It'd be something like this in the `profileForm`:

```haskell
-- The `Just nextFreeDay` is the important part
areq (dateField takenDays tomorrow) (fs "Date" []) (Just nextFreeDay)
```

**Comment by gabebw** [comment]
After #54 and #57, Croniker:

* shows a friendly error if the user selects a taken date
* defaults the date select box to the next available date

I think that solves this problem, so I'm closing this issue.
