### ISSUE TITLE
Use a form-specific model (Form.Timezone?) in Handler.UpdateUser

### ISSUE THREAD

**Issue by gabebw** [gabebw/croniker#72]
Check [this](https://github.com/gabebw/croniker/blob/d4ab883b0234aed9921c92c86a46391b6a9ab059/Handler/UpdateUser.hs#L23-L30) out:

```haskell
timezoneForm User{..} = renderDivs $ User
       <$> pure userTwitterUserId
       <*> pure userTwitterUsername
       <*> pure userTwitterOauthToken
       <*> pure userTwitterOauthTokenSecret
       <*> areq (selectFieldList selectTZs) "" Nothing
       <*> pure False
       <*> pure False
```

There's only one form field in there, the `areq` to select the user's time zone. It'd be much nicer as something like:

```haskell
timezoneForm = renderDivs $ TimezoneForm
    <$> areq (selectFieldList selectTZs) "" Nothing
```

**Comment by tonyd256** [comment]
Seems like the low hanging fruit would be to remove all the applys and `pure`s up to that point at least ... if that was the last field then you could remove the others too

**Comment by tonyd256** [comment]
wait a second ... you're pulling apart a `User` to recreate a `User`? Could you use record syntax like so?

```
timezoneForm user = renderDivs $ setTimezone user <$> areq ...
  where
    setTimezone u tz = u { timezone = tz }
```
