### ISSUE TITLE
Add `created_at` and `updated_at` to User and Profile

### ISSUE THREAD

**Issue by gabebw** [gabebw/croniker#77]
```haskell
createdAt <- liftIO getCurrentTime
```

**Comment by tonyd256** [comment]
If you don't need them in the code but just want them for database debugging/reference you can do this:
https://github.com/November-Project/tracker-api/blob/master/config/models#L16
https://github.com/November-Project/tracker-api/blob/master/database/date-triggers.sql

**Comment by gabebw** [comment]
Oooooh [MigrationOnly](https://github.com/yesodweb/persistent/wiki/Persistent-entity-syntax#migrationonly).

And yes, it's just for reference, I don't expect to use them in the code.

**Comment by gabebw** [comment]
Oh dang, _and_ I can change the `user` table to `users` with `User sql=users`! At last, no more double-quoting the table every time I use it! Your `config/models` is a _treasure_.

**Comment by tonyd256** [comment]
haha thanks!

**Comment by tonyd256** [comment]
it took me so long to figure out some of that stuff. re: tough docs on yesod
